# fly.toml app configuration file generated for catapi on 2023-10-29T21:39:04-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "catapi"
primary_region = "sea"

[build]

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 1
max_machines_running = 1
processes = ["app"]

[env]
GIN_MODE = "release"
LISTEN_PORT = "8080"
